"""Constantes globales y paleta de colores de METEOR STRIKE."""

from __future__ import annotations

import os

ANCHO = 854
ALTO = 480
FPS = 60
DT_MAXIMO = 0.05

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
RUTA_ASSETS = os.path.join(BASE_DIR, "assets")
RUTA_SPRITE_NAVE = os.path.join(RUTA_ASSETS, "nave001.png")
RUTA_FUENTE_RETRO = os.path.join(RUTA_ASSETS, "fuente_retro.ttf")
RUTA_HISTORIAL_PUNTAJES = os.path.join(BASE_DIR, "historial_puntajes.json")

COLORES = {
    "fondo": (7, 8, 15),
    "fondo_panel": (14, 16, 32),
    "primario": (77, 255, 210),
    "primario_medio": (26, 170, 136),
    "primario_oscuro": (13, 85, 68),
    "secundario": (255, 153, 68),
    "secundario_medio": (204, 85, 0),
    "secundario_oscuro": (102, 34, 0),
    "acento": (255, 224, 102),
    "peligro": (255, 51, 34),
    "neutro_claro": (200, 204, 216),
    "neutro_medio": (106, 110, 128),
    "neutro_oscuro": (42, 45, 58),
    "blanco": (232, 232, 232),
}

DIFICULTAD = {
    "facil": {"vel_meteorito": (60, 100), "intervalo_spawn": 2.5, "hp_max": 1, "enfriamiento": 0.6},
    "medio": {"vel_meteorito": (100, 160), "intervalo_spawn": 1.8, "hp_max": 2, "enfriamiento": 0.45},
    "dificil": {"vel_meteorito": (160, 240), "intervalo_spawn": 1.0, "hp_max": 3, "enfriamiento": 0.3},
}

PUNTOS_DESTRUIR = 10
PUNTOS_ESQUIVAR = 5
PUNTOS_EMPATE = 10000
VIDAS_INICIALES = 3
DURACION_NIVEL = 60
TIEMPO_INVENCIBLE = 1.5

TAMANO_NAVE = (64, 32)
TAMANO_BALA = (10, 4)
TAMANO_MINI_NAVE = (20, 10)
VELOCIDAD_NAVE = 250
VELOCIDAD_BALA = 400
PORCENTAJE_LIMITE_NAVE_X = 0.7
MARGEN_NAVE = 8

RADIO_METEORITO_MIN = 18
RADIO_METEORITO_MAX = 32
VERTICES_METEORITO_MIN = 8
VERTICES_METEORITO_MAX = 10
VARIACION_RADIO_VERTICE_MIN = 0.72
VARIACION_RADIO_VERTICE_MAX = 1.18
DERIVA_Y_METEORITO_MIN = -30
DERIVA_Y_METEORITO_MAX = 30
DESPLAZAMIENTO_METEORITO_X = 0
FLASH_METEORITO = 0.1

FRAMES_EXPLOSION = 4
TIEMPO_FRAME_EXPLOSION = 0.08
RADIO_PARTICULA_EXPLOSION = 3
TAMANO_EXPLOSION = 72

ESTRELLAS = 150
ESTRELLAS_POR_CAPA = (60, 50, 40)
VELOCIDAD_ESTRELLAS = (18, 28, 42)
TAMANO_ESTRELLA_MIN = 1
TAMANO_ESTRELLA_MAX = 2
PARPADEO_TITULO = 500

ANCHO_BOTON_MENU = 170
ALTO_BOTON_MENU = 54
TAMANO_BOTON_MENU = ANCHO_BOTON_MENU
ANCHO_BOTON_CAMBIO = 170
ALTO_BOTON_CAMBIO = 54
TAMANO_BOTON_CAMBIO = ANCHO_BOTON_CAMBIO
ANCHO_BOTON_OPCIONES = 132
ALTO_BOTON_OPCIONES = 32
TAMANO_BOTON_OPCIONES = ANCHO_BOTON_OPCIONES

MAX_HISTORIAL_PUNTAJES = 8
CANTIDAD_INICIALES = 3
ANCHO_MODAL_OPCIONES = 360
ALTO_MODAL_OPCIONES = 260
ALTO_CABECERA_MODAL = 48
ALPHA_OVERLAY = 180
SLIDER_ANCHO = 200
SLIDER_ALTO = 6
TAMANO_MANGO_SLIDER = 14
ANCHO_BOTON_MODAL = 140
ALTO_BOTON_MODAL = 34

ANCHO_DIVISORIA_VS = 2
ALTO_VISTA_VS = ALTO // 2
PORCENTAJE_EMPATE = PUNTOS_EMPATE

FUENTE_FALLBACK = "monospace"
TAMANO_TITULO = 34
TAMANO_SUBTITULO = 18
TAMANO_NORMAL = 14
TAMANO_PEQUENO = 11

MARGEN_GENERAL = 12
MARGEN_UI = 10

TEXTO_OPCIONES = "OPCIONES"
TEXTO_REANUDAR = "REANUDAR"
TEXTO_MENU = "MENÚ PRINCIPAL"
TEXTO_REINTENTAR = "REINTENTAR"
